### ISSUE TITLE
English variable names instead of (probably) spanish. 

### ISSUE THREAD

**Issue by adriankiezik** [Manolito368/Epic-Cheese#1]
As the title says. My small suggestion to make code more readable. 

Also, is the cheese biome already working? 😳

**Comment by Manolito368** [comment]
yes, I will change the code to English but it requires changing a lot of code and it is easier for me to understand it like this.
and the cheese biome and dimension it's WIP, I have something done but until it works well it won't be here :)

**Comment by Manolito368** [comment]
ok, now all the things are in english instead of spanish, I just had to stop playing zelda botw for 1 hour XD
